[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "examples"
version = "0.1.dev0"
license = {file = "LICENSE-CODE"}
description = "个人测试子模块"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "autogen-core",
    "autogen-ext",
    "autogen-agentchat",
    "langfuse>=2.54.1",
    "litellm>=1.51.3",
    "llama-index>=0.11.20",
    "llama-index-agent-openai>=0.3.4",
    "llama-index-llms-openai-like>=0.2.0",
    "llama-index-llms-ollama>=0.3.6",
]

[tool.uv]
dev-dependencies = []


[tool.ruff]
extend = "../../pyproject.toml"
include = ["src/**", "tests/*.py"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
test = "pytest -n auto"
